name: Wagcount
options:
  bundleIdPrefix: com.shimondeitel.walktrack
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Wagcount:
    type: application
    platform: iOS
    sources:
      - path: Wagcount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.walktrack
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Wagcount/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  WagcountTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: WagcountTests
      - path: Wagcount.storekit
    dependencies:
      - target: Wagcount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.walktrack.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  WagcountUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: WagcountUITests
    dependencies:
      - target: Wagcount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.walktrack.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Wagcount:
    build:
      targets:
        Wagcount: all
        WagcountTests: [test]
        WagcountUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Wagcount.storekit
    test:
      config: Debug
      storeKitConfiguration: Wagcount.storekit
      targets:
        - WagcountTests
        - WagcountUITests
    archive:
      config: Release
